# Generated by Django 3.1.2 on 2020-11-22 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='job_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('job_kind', models.CharField(max_length=10)),
                ('salary', models.CharField(max_length=10)),
                ('date', models.CharField(max_length=10)),
                ('jobtime', models.CharField(max_length=15)),
                ('locate', models.CharField(max_length=15)),
                ('infomation', models.CharField(max_length=30)),
            ],
        ),
    ]
