# Generated by Django 3.1.2 on 2020-11-22 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0002_auto_20201122_2138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job_info',
            name='date',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='job_info',
            name='information',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='job_info',
            name='job_kind',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='job_info',
            name='jobtime',
            field=models.CharField(max_length=35),
        ),
        migrations.AlterField(
            model_name='job_info',
            name='locate',
            field=models.CharField(max_length=35),
        ),
        migrations.AlterField(
            model_name='job_info',
            name='name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='job_info',
            name='salary',
            field=models.CharField(max_length=30),
        ),
    ]
