# Generated by Django 3.1.2 on 2021-03-04 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0005_auto_20210304_1219'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job_info',
            old_name='publish',
            new_name='publisher',
        ),
    ]
