# Generated by Django 3.1.2 on 2021-03-06 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0006_auto_20210304_2114'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User_selected',
            new_name='User_collect',
        ),
    ]
