# Generated by Django 3.1.2 on 2021-03-26 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0007_auto_20210306_2239'),
    ]

    operations = [
        migrations.AddField(
            model_name='job_info',
            name='index',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='openid',
            field=models.CharField(db_index=True, max_length=220, primary_key=True, serialize=False),
        ),
    ]
